### PR TITLE
feat: add security.txt

### LINKED ISSUE #25: Add `security.txt` file to make it easier for security researchers to submit security vulnerability reports
## Description

It's a copy of kawalcovid19/wargabantuwarga.com#482

The main purpose of `security.txt` is to help make things easier for companies and security researchers when they want to get in touch with us about security issues.

The https://securitytxt.org/ website provides a generator for the `security.txt` file as well as a FAQ, and the technical standard (draft) can be viewed [here](https://tools.ietf.org/html/draft-foudil-securitytxt-12).

## Implementation Model

- Generate a `security.txt` file using https://securitytxt.org/ - make sure that the email used for this text file is active *and* secure.
- Make sure to set an expiration period for the `security.txt` to be 1 year at the latest. We need to also make sure that these credentials get properly rotated when we need to renew these details.
- Place the `security.txt` file in the `.well-known` folder of our root site directory: `public/.well-known/security.txt`

## Tasks

- [ ] Generate the `security.txt` file using the requirements listed above.

### PR DESCRIPTION
**Pull request by asaadam**
Closes #25 

## Description

add security.txt

 I think we can add Canonical, but I don't know what's the domain for this site.

### CODE REVIEW

**Comment by zainfathoni** [comment]
Mas @ramarahmanda, on which domain are we expected to host this app?

**Comment by ramarahmanda** [comment]
> Mas @ramarahmanda, on which domain are we expected to host this app?

I think for the production it will use `silacak3.kemenkes.go.id`. But we haven't created it yet.

**Comment by asaadam** [comment]
@zainfathoni I think we can merge it now? 
later on, we will add canonical url

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks, @asaadam!

**Comment by zainfathoni** [comment]
@all-contributors please add @asaadam for security

**Pull request merged**
