### PR TITLE
Feat: Close Contact Detail Page

### PR DESCRIPTION
**Pull request by hanihusam**
Closes  #37 

## Description

This page displays the detail of a close contact case. This page can be accessed by clicking "Lihat Detail" on close contact list in confirmed case detail

## Current Tasks

- [x] Implementing the design
- [ ] Test

### CODE REVIEW

**Comment by hanihusam** [comment]
Can I make adjustment for the layout? @zainfathoni @resir014
Also I think I will create an issue for the `Card` component. I see the card, esp card title is used in some cases. wdyt?

**Comment by resir014** [comment]
@hanihusam Yes, please create an issue item for any improvements to the design system as you see fit.

**Review by zainfathoni — APPROVED** [review]
LGTM 💯 

Thanks for contributing, @hanihusam! 🙏

**Comment by zainfathoni** [comment]
@all-contributors please add @hanihusam for code

**Pull request merged**
