### PR TITLE
feat: confirmed cases list

### LINKED ISSUE #30: Confirmed case
## Description

This page contains list of confirmed cases by _puskesmas_ . Each row in table represent people that has been confirmed for covid19 case (data from NAR). We can add close contact for each confirmed case or look confirmed case profile. 

Figma: https://www.figma.com/file/a4l6zqfnLyjG9h9Qyj6QsE/Silacak?node-id=12%3A1594

## Tasks

- [ ] Selected _puskesmas_
- [ ] Id & Title _puskesmas_
- [ ] Tab to change to other list
- [ ] Filter/search confirmed case by nik & name
- [ ] Confirmed case table

### PR DESCRIPTION
**Pull request by resir014**
Closes #30

## Description

Confirmed cases list page.

image

## Current Tasks

- [ ] Create page layout
- [ ] Create mobile design, make it responsive.
- [ ] Use `swr` to wrap fetch data
- [ ] Tests

### CODE REVIEW

**Comment by resir014** [comment]
Since we're focusing on the mobile design first, both me and @zainfathoni have decided to go forward with the mobile design, with the cases list design slightly tweaked to use a modified version of the [Stacked List](https://tailwindui.com/components/application-ui/lists/stacked-lists#component-371ccbef96ba57325d261f1b74afdd41) from Tailwind UI.

Since the desktop design uses an entirely different pattern (table instead of stacked lists), we think that it's better for us to keep things simple and iterate on the stacked list design.

image

image

**Comment by resir014** [comment]
Final layout:

**Mobile**

image

**Desktop**

image

**Comment by zainfathoni** [comment]
Can we make the flex-direction of the buttons vertical in this viewport only?

On the mobile view, we need to make it horizontal again, though. 😁 

Screenshot 2021-08-14 at 14 38 11

**Review by zainfathoni — APPROVED** [review]
LGTM :100:

Thanks, @resir014!

**Comment by zainfathoni** [comment]
@all-contributors please add @resir014 for code, design, infra, maintenance, project management, review, security, and tool.

**Comment by zainfathoni** [comment]
@all-contributors please add @resir014 for doc.

**Pull request merged**
